(package "ffpc"
         "0.1.0"
         "Find file in project or current directory")

(website-url "https://github.com/jcs-elpa/ffpc")
(keywords "lisp")

(package-file "ffpc.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "jcs-elpa")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "dash")
(depends-on "f")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
